### PR TITLE
Support tablespace for partitioning

### PR DESCRIPTION
**Pull request by trietphm**
- Add option to specify the tablespace that the partitions will be stored

### CODE REVIEW

**Comment by ankane** [comment]
Hey @trietphm, thanks for the PR! Can you give a bit more context about how you're using tablespaces with partitioning? Also, does it make sense for the parent table to share the same tablespace?

**Comment by trietphm** [comment]
Our database has two main tablespaces: `slow_tablespace` and `fast_tablespace`. 
- `slow_tablespace`'s location is set to the HDD disks and is for the data that does not require really good IO performance. Mostly for tracking, archiving data.
- And `fast_tablespace` - the default tablespace for all other tables which points to the SSD disks.

The old ordinary table is in `slow_tablespace` and I want to put the partitioned table there as well.
IMO, it does not matter which tablespace that the parent will be put since there is no data in that table. Right now, the parent table is created in the default tablespace, not the same tablespace as the old one.

**Comment by ankane** [comment]
Thanks @trietphm, that's really helpful. It sounds like pgslice could use the tablespace from the original table in the `prep` command and then carry that to the partitions, but I like the simplicity of this approach. A few thoughts on the code:

1. Let's use the `quote_ident()` method around the `tablespace` when building SQL
2. From my testing, the tablespace needs to come after `INHERITS ()` for the trigger-based approach

**Comment by trietphm** [comment]
Yeah, you're right. Updated 👍

**Comment by ankane** [comment]
Thanks @trietphm! Will push out a new release shortly.

**Pull request merged**
