### PR TITLE
add --batch-size and --sleep defaults to readme

### PR DESCRIPTION
**Pull request by acrogenesis**
Add --batch-size and --sleep defaults to readme.

Thanks for this awesome tool!

### CODE REVIEW

**Comment by benschwarz** [comment]
@acrogenesis Thanks for adding the defaults, they're helpful to have surfaced on the README 👍 

Do you think it'd be possible to also add notes for the other `fill` flags also?

**Comment by sdhull** [comment]
@benschwarz what are the other `fill` flags?

**Comment by benschwarz** [comment]
Been a while, had to check the source. I think what I meant was that the `pgslice fill` command has [several undocumented flags](https://github.com/ankane/pgslice/blob/master/lib/pgslice/cli/fill.rb#L4-L10): `batch_size`, `swapped`, `source_table`, `dest_table`, `start`, `where` and `sleep`.

It would be great to include them in this or another PR.

**Comment by ankane** [comment]
Thanks @acrogenesis!

@benschwarz re other flags: some are already included in the readme, and the rest should rarely be needed.

**Pull request merged**
