### PR TITLE
Fail on text-valued PKs; change test env var

### PR DESCRIPTION
**Pull request by wkalt**
Update non-numeric PK handling to fail on text as well as UUID.

### CODE REVIEW

**Comment by wkalt** [comment]
@ankane any thoughts on testing for the datatype handling change? Maybe a new "invalid" table in test_helpers for such failure cases?

**Comment by wkalt** [comment]
added some tests to the first commit

**Comment by ankane** [comment]
Hey @wkalt, thanks for the PR 👍 What if we check that max_source_id is nil or numeric? I think it’ll be cleaner than keeping a list of numeric types.

**Comment by wkalt** [comment]
@ankane thanks for having a look -- I'll make the change when I get a chance.

Thinking about the underlying issue of UUID support for a minute, it seems to me like it should be possible to support.

What if when pgslice fails to detect a numeric PK it did roughly the following?

```
create sequence pgslice_customers_id_seq;
alter table customers add column pgslice_id bigint;
alter table customers alter column pgslice_id set default nextval('pgslice_customers_id_seq');
```

Now we have all ongoing inserts ordered by the sequence value. PGslice can use the new column in the same way it uses the PK currently, just with the awareness the nullls correspond to "old" data that will be transferred in the initial select. When everything is finished up, the column and sequence can be dropped.

I'll explore this approach for my own purposes and report back.

**Comment by ankane** [comment]
I don't think it's a good idea for pgslice to modify the source table. It sounds like a pattern that can be done manually for those who need it. Would need to think about the best way to handle nulls without making it overly complicated.

**Comment by ankane** [comment]
Cleaning up stale PRs

**Pull request closed without merging**
